eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # defaultZone: http://localhost:8761/eureka/
      defaultZone: http://192.168.18.23:8761/eureka/
  instance:
    # hostname: localhost
    hostname: 192.168.18.23

management:
  endpoints:
    web:
      exposure:
        include: "*"
        
